services:
  server:
    image: wasm-example
    build:
      context: .
      platforms:
        - wasi/wasm32
    ports:
      - 8080:8080
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1
